export const GET_DETAIL_SEEKER_PENDING = "GET_DETAIL_SEEKER_PENDING";
export const GET_DETAIL_SEEKER_SUCCESS = "GET_DETAIL_SEEKER_SUCCESS";
export const GET_DETAIL_SEEKER_FAILED = "GET_DETAIL_SEEKER_FAILED";

export const GET_DETAIL_RECRUITER_PENDING = "GET_DETAIL_RECRUITER_PENDING";
export const GET_DETAIL_RECRUITER_SUCCESS = "GET_DETAIL_RECRUITER_SUCCESS";
export const GET_DETAIL_RECRUITER_FAILED = "GET_DETAIL_RECRUITER_FAILED";
